apiVersion: v1
kind: Template
metadata:
  name: ultrahook-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ultrahook
  type: Opaque
  data:
    api.key: ${ULTRAHOOK_API_KEY}
parameters:
- name: ULTRAHOOK_API_KEY
  required: true